const phrases = [
  "Well, that didn\u2019t do anything. Try again!",
  "Keep calm and press again.",
  "Oops, nothing happened. But you\u2019re doing great!",
  "This button is practicing social distancing. Keep going!",
  "Looks like this button is on a break. Keep at it!",
  "Nothing to see here\u2014just a motivational nudge!",
  "You\u2019re doing awesome! This button is just here for moral support.",
  "Sometimes, you just need to press a button and keep going.",
  "Not much happened, but hey, perseverance is key!",
  "Button pressed! Congratulations on taking action!",
  "You clicked the button! That\u2019s the real achievement.",
  "It\u2019s not the button, it\u2019s the journey. Keep clicking!",
  "Button\u2019s on vacation. You\u2019re still on track!",
  "This button believes in you. Keep pushing!",
  "The button has taken a nap. You keep going, though!",
  "Well, that was anticlimactic. But hey, you\u2019re on the right track!",
  "This button is a fan of the \u2018keep going\u2019 movement.",
  "Click again for more nothingness! You\u2019re doing fantastic!",
  "You\u2019re a champion! This button\u2019s just here to cheer you on.",
  "No fireworks here, just pure encouragement. Keep going!",
  "Congratulations! You\u2019ve successfully clicked the button. Now, keep at it!",
  "The button\u2019s just taking a breather. Your journey continues!",
  "This button\u2019s specialty: doing nothing and still cheering you on!",
  "Clicking this button is a step in the right direction. Keep moving!",
  "Nothing happened, but you\u2019re doing an amazing job! Keep clicking!",
  "The button\u2019s asleep, but your progress is wide awake!",
  "This button might be lazy, but you\u2019re not! Keep pushing forward!",
  "Just a friendly reminder that you\u2019re doing great\u2014keep going!",
  "Click here for extra motivation. No actual change, just encouragement!",
  "No results here, just a virtual high-five. Keep going!"
]

export default phrases